# Generated by Django 4.2.7 on 2023-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion_taller',
            name='id',
        ),
        migrations.AlterField(
            model_name='postulacion_taller',
            name='Idpostulacion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
