# Generated by Django 3.1.2 on 2023-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
