# Generated by Django 3.1.2 on 2023-07-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactform_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='vigente',
            new_name='disponible',
        ),
    ]
