# Generated by Django 4.2.7 on 2023-12-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inscripcion_remove_talleres_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion_taller',
            name='promedio',
        ),
    ]
