# Generated by Django 3.1.2 on 2023-07-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230716_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='agregados',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
