# Generated by Django 3.1.2 on 2023-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230716_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
