# Generated by Django 3.1.2 on 2023-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230716_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='asunto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='mensaje',
            field=models.TextField(max_length=100),
        ),
    ]
