# Generated by Django 3.1.2 on 2023-07-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230716_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='asunto',
            field=models.CharField(max_length=50),
        ),
    ]
