# Generated by Django 4.2.7 on 2023-11-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230716_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='adulto_mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=70)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('frecuencia', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_credencial', models.IntegerField(blank=True, null=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('sueldo_base', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMuni', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('url_pag_web', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMuni', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='postulacion_instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_postulacion', models.IntegerField(blank=True, null=True)),
                ('fecha_postulacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('aceptado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='postulacion_taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('cupos', models.IntegerField(blank=True, null=True)),
                ('promedio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=70)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=70)),
                ('horas', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
