# Generated by Django 4.2.7 on 2023-11-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pago_idmuni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talleres',
            old_name='Idtalleres',
            new_name='idtalleres',
        ),
    ]
